### ISSUE TITLE
water boundary lines from OSM are missing

### ISSUE THREAD

**Issue by kkowalsky** [tilezen/vector-datasource#1153] opened 2017-01-12 22:45 UTC
* Waterlines [boundary = true] aren't showing up in a smooth line (more like random dots) at zooms 9 and higher. 
* Should continue to be a line, like other areas around the world 
* Eastern coast of Italy, near Ancona or Pescara

![waterlines](https://cloud.githubusercontent.com/assets/4246770/21911468/bf7a1330-d8d5-11e6-9dd7-b68d802cc22f.gif)

**Comment by nvkelso** [comment] 2017-01-12 23:24
Duplicate of #735.

**Closed by nvkelso** 2017-01-12 23:24 UTC
