### ISSUE TITLE
Buildings at lower zoom levels

### ISSUE THREAD

**Issue by schnuerle** [tilezen/vector-datasource#234] opened 2015-09-23 13:15 UTC
It would be nice to at least have the option to show buidings at lower zoom levels (more zoomed out).  Currently you can see them at 14, at 13 you see 'large' ones, and at 12 they are all gone.

Referencing this [post from Mapzen](https://mapzen.com/blog/getting-crafty), in Oct 2014 there were more buildings than streets, signifying their importance in OSM.  Having worked on large scale OSM imports, it would be nice to have an easy way online to show a city's builidngs at a glance, without having to process OSM exports.  

At zoom levels 12 and 11 building geometry could be simplified even more than at 14, like they are currently when going from 15 to 14 and from 15 to 16.  At 10 and 9 or lower, the could become points.  If people did no not want to show buildings at these zoom levels, then they can turn them off using "minzoom" : "13".

**Comment by nvkelso** [comment] 2015-09-23 23:13
I like the idea, but I'm not sure this should go into standard tiles used for basemap cartography. I can see including buildings a few zooms earlier... but part of this feels more like a new specialized data tile feature (to degrade the buildings to points to keep showing them even out to zoom 0). To get you by in the meantime, have you tried CartoDB?

**Comment by schnuerle** [comment] 2015-09-24 14:27
It seems you should at least be able to see where every building in a city is, in one browser view.  Right now the last time you can see all the buildings is zoom 14.  To get a city (like say DC), you should go to 11, then maybe at 10 you show the large buildings only.  But it still seems the polygons could just keep getting simplified at each lower zoom level, just like they do now (it's pretty noticable when zooming, but fine when viewing one static zoom level).

I also am not saying that all buildings should be on be default for everyone viewing the standard tiles.  I'm just suggesting that if I am making a custom style, I should be able to turn on buildings at lower zoom levels to see them if I'd like.  Right now there is a hard cut off of zoom 14 and 13 for buildings, so styling them a lower zoom levels manually isn't possible.

I don't think CartoDB lets you style the underying OSM data and make custom style adjustments to tags, like say Mapbox does.  You can choose from some existing tilesets, or upload your own pregenerated ones, but that's not the same thing.

**Comment by bcamper** [comment] 2015-09-24 15:14
@schnuerle got it. The problem is that there's a balance between what is sufficiently useful for everyday use cases (which this tile set is intended for), vs. addition tile weight (network size + time) that everyone else has to absorb even if they don't use that data. Because most everyday maps don't need *all* buildings at z13, we start winnowing the buildings (I believe by area) at that point. I think you will find the same is true in Mapbox's and other vector tile sets. As @nvkelso says, a possible alternative (which we are not able to do at present but would consider in the future) would be to have additional tile sets for more specific use cases.

**Comment by nvkelso** [comment] 2017-06-27 23:51
Closing.

**Closed by nvkelso** 2017-06-27 23:51 UTC
