### ISSUE TITLE
broken pipe exception in mapbox vector tile

### ISSUE THREAD

**Issue by mnameghi** [tilezen/vector-datasource#1256] opened 2017-05-21 13:20 UTC
When I used vector tile and request a tile with more detail, an error occurred.

```python
Exception happened during processing of request from ('192.168.5.109', 35261)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```
My map is a simple road map just have major road from osm.

**Comment by nvkelso** [comment] 2017-05-21 14:49
Sorry to hear about your issue. Can you provide more reproduction details, please?

- How did you load your database?
- Is your YAML query file available for debug?
- is it just that tile that causes issues, have you ever gotten a good tile out?
- what versions of vector data source and Mapbox vector tile are you using? Also tileserver.

Please share either here or email nathaniel at Mapzen.com.

**Comment by mnameghi** [comment] 2017-05-22 03:25
Hi
thanks for response. I used postgres database and I made a simple yaml. this is my yaml:
```yaml
all:
  - my_layer
layers:
  my_layer:
    template: my_layer.jinja2
    start_zoom: 9
    simplify_start: 9
    simplify_before_intersect: true
    geometry_types: [LineString]
    transform:
      - vectordatasource.transform.remove_feature_id
      - vectordatasource.transform.truncate_min_zoom_to_2dp
    area-inclusion-threshold: 1
```
and this is query template:
```jinja
SELECT
    {% filter geometry %}shape{% endfilter %} AS __geometry__,
    highway, id AS __id__

FROM my_table

WHERE
    {{ bounds['line']|bbox_filter('shape',3857) }}
```
When I used vector tile in high level zoom level like 17 and 18 everything is OK, but when I zoom back this error occurred.

**Comment by zerebubuth** [comment] 2017-05-22 13:36
```
Exception happened during processing of request from ('192.168.5.109', 35261)
Traceback (most recent call last):
...
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

I've seen errors like the above when the web browser disconnects before the tile server has been able to send all the response back. There are many reasons why this might be happening, but two I've seen several times before are:

1. The tile server is taking too long to respond, and the web browser closes the connection after a timeout.
2. The tile is in the wrong format (e.g: JSON was expected, but MVT is sent) and the browser closes the connection when it can't parse the first few bytes.

Are there any errors on your browser's javascript console, or in the inspector / firebug consoles which might indicate if either of these are happening?

**Comment by mnameghi** [comment] 2017-05-23 03:39
Can I change tile server timeout where it is slow?

**Comment by zerebubuth** [comment] 2017-05-23 12:58
If it is timing out, then it's probably the browser which is closing the connection rather than tileserver. I don't know if there's any way to increase the browser timeout. If that is the problem, then there might be other things which would fix it. For example, if the query is slow, then adding a spatial index in the database might help.

Which fix would be appropriate really depends on what the problem is. Does the browser console say that the tile request timed out?

**Comment by musicformellons** [comment] 2017-06-20 11:42
I am having same issue (custom tile-layer on postgres on a remote server, combined in the browser with mapzen vector tile service):
```
Exception happened during processing of request from ('ipaddress', 38054)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

query template:
```
SELECT
    ogc_fid AS __id__,
    {% filter geometry %}wkb_geometry{% endfilter %} AS __geometry__,
    url AS url,
    image AS image,
    city AS city
FROM customlayer
```

And yaml:

```
all:
  - customlayer.jinja2
layers: 
  customlayer:
    template: customlayer.jinja2
    start_zoom: 1
    geometry_types: [Point]
    transform: []
    area-inclusion-threshold: 1
```
I have something like 50 thousand points in the database. It works but is very slow and I regularly get the pipe error, also it hangs quite often (blinking cursor, no tiles are returned anymore). My questions:
1) I thought when a tile is requested it is cached, so should be quick next time, right? When I restart the server is the cache cleared or something as performance is back to slow again then, correct?
2) How I debug the 'hangs' as I do not get error-messages? I can restart the tileserver and then it works fine for a while.

I am seeing this error in the browser when tileserver 'hangs':
```
GET http://<ipaddress>:8080/all/11/1023/681.mvt net::ERR_CONNECTION_RESET
mapbox-gl.js?31ef:411 [object ProgressEvent]
Evented.fire @ mapbox-gl.js?31ef:411
Evented.fire @ mapbox-gl.js?31ef:411
Evented.fire @ mapbox-gl.js?31ef:411
t._tileLoaded @ mapbox-gl.js?31ef:191
i @ mapbox-gl.js?31ef:199
Actor.receive @ mapbox-gl.js?31ef:391
```
I am not sure about whether the pipe error gives me an error message in the browser. Having problems to reproduce the error now... 

I will try to speed up the query.

**Comment by rmarianski** [comment] 2017-06-20 13:23
> I thought when a tile is requested it is cached, so should be quick next time, right? When I restart the server is the cache cleared or something as performance is back to slow again then, correct?

Only when caching is configured:

https://github.com/tilezen/tileserver/blob/07dce7a6ff7a034e79a2fbcd074496bf366deff2/config.yaml.sample#L44-L56

**Closed** 2017-06-20 20:42 UTC
