### ISSUE TITLE
Unexpected text related to "name:ko"

### ISSUE THREAD

**Issue by hhsoft** [tilezen/vector-datasource#1165] opened 2017-02-15 08:19 UTC
* **What did you see?**
Value of "name:ko" of some cities/regions are not correct in tiles.
For example, "Hadongni (415160952)"'s "name:ko(in OSM)" is "하동리". But value of "name:ko(in tile)" is "Hadongni".
It seems that value of "name:ko(in tile)" is "name:ko_rm(in OSM)" or "name:ko_hanja(in OSM)" instead of "name:ko(in OSM)."

* **What did you expect to see?** 
Both "name:ko_rm" and "name:ko_hanja" are totally different from "name:ko".

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

case 1. "name:ko_rm(in OSM)" vs. "name:ko(in tile)"
하동리 / Hadongni (415160952) 
http://www.openstreetmap.org/api/0.6/node/415160952
https://tile.mapzen.com/mapzen/vector/v1/all/13/6997/3208.topojson
(search "name:ko":"Hadongni")

case 2. "name:ko_hanja(in OSM)" vs. "name:ko(in tile)"
경기도 / Gyeonggi (4549670214)
http://www.openstreetmap.org/api/0.6/node/4549670214
https://tile.mapzen.com/mapzen/vector/v1/all/11/1747/794.topojson
(search "name:ko":"\u4eac\u757f\u9053")

**Comment by nvkelso** [comment] 2017-02-15 18:11
We consider this a data error. To fix it add `name:ko` of `하동리` to the [node](http://www.openstreetmap.org/api/0.6/node/415160952).

**Comment by nvkelso** [comment] 2017-02-15 19:03
I've updated these two examples in OSM with change set: 

- https://www.openstreetmap.org/changeset/46116059

**Comment by chyangpa** [comment] 2017-02-16 07:04
The issue is not only about `Hadongni` and `Gyeonggi`. In addition to the above two cases, there are many cases of data error involving `name:ko` in Mapzen tiles.

@nvkelso Despite your kind effort, `name:ko` has already been added to the nodes in the above two cases. Therefore, it is seen as a problem when **converting data incorrectly from OSM data to Mapzen tiles**, rather than OSM data errors.

**Comment by nvkelso** [comment] 2017-02-17 22:13
@chyangpa Can you confirm you'd like the order of operations to be:

- When there is `name:ko` in the OSM data:
  - Export that as `name:ko` in Tilezen, but...
- If no `name:ko` in the OSM data:
  - First look in `name:ko_rm` in OSM to export as `name:ko` in Tilezen, else
  - Fallback to `name:ko_hanja` in OSM for the export as `name:ko` instead?

We can look into that, but I still maintain that if the data is properly on the features in OSM, it will come thru as you expect it.

**Comment by nvkelso** [comment] 2019-02-13 01:56
There's been quite a big of data churn in Korea since this issue was filed, closing for now.

**Closed by nvkelso** 2019-02-13 01:56 UTC
Labels: loe medium
