### ISSUE TITLE
Buildings get no heights

### ISSUE THREAD

**Issue by pyalot** [tilezen/vector-datasource#1255] opened 2017-05-18 09:57 UTC
I am using the mapzen vector tile service to visualize buildings in 3D.

A problem I have noticed is that building heights seem to be largely missing. For example this is how the heights (feature.properties.height) look for [the tile for the coordinates -73.9712724, 40.7646611](https://tile.mapzen.com/mapzen/vector/v1/buildings/15/9650/12313.json?api_key=mapzen-KkpHGEo) and zoom 15 (corner of central park in Manhattan) in our application (missing heights are set to a constant 10m):

![image](https://cloud.githubusercontent.com/assets/592826/26197087/5853e416-3bc1-11e7-8710-07ac72369e12.png)

This is how the heights look in the [CaesiumJS demo](https://cesiumjs.org/NewYork/index.html?view=-73.97219119960221%2C40.77133713311895%2C347.7065244401054%2C186.1349682878918%2C-23.629808565813423%2C359.97784049960705) of the same location with the OpenStreetmaps dataset:

![image](https://cloud.githubusercontent.com/assets/592826/26196888/ab9d554a-3bc0-11e7-8b4b-43e85980f8ef.png)

For reference here's the [google maps](https://www.google.com/maps/place/Manhattan,+New+York,+NY/@40.7702578,-73.9728072,405a,35y,179.71h,58.73t/data=!3m1!1e3!4m5!3m4!1s0x89c2588f046ee661:0xa0b3281fcecc08c!8m2!3d40.7830603!4d-73.9712488) view of the same corner:

![image](https://cloud.githubusercontent.com/assets/592826/26197103/65a7a850-3bc1-11e7-9df5-6402aadca7ff.png)

As is evident OpenStreetmap data does contain relatively accurate heights. However the mapzen tiles do not seem to contain these.

**Comment by zerebubuth** [comment] 2017-05-18 10:46
Hi Florian,

Thanks for getting in touch.

Perhaps you could give us some more information about how you're accessing the tiles, and the exact tile coordinates you're using?

I took a look at the area you mention using one of our "house styles" called "bubble wrap", and it [shows the corner of Central Park like this](http://tangrams.github.io/bubble-wrap/#17/40.76462/-73.97332) (note that it's north-up, so opposite to the screenshots you've shown):

![image](https://cloud.githubusercontent.com/assets/271360/26197819/91e1c104-3bbb-11e7-825d-12d6fd8be723.png)

Digging into the data, one of the buildings which appears to be getting a default height of 10m in your example is the Plaza Hotel, which has a [height of 85m in the OSM data](http://www.openstreetmap.org/way/265147728). When I look at tile `15/9650/12313` in the `buildings` layer, I see this:

```json
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -73.975112,
              40.764428
            ],
            [
              -73.974948,
              40.764662
            ],
            [
              -73.974796,
              40.7646
            ],
            [
              -73.974638,
              40.764872
            ],
            [
              -73.973868,
              40.764526
            ],
            [
              -73.974195,
              40.764056
            ],
            [
              -73.975112,
              40.764428
            ]
          ]
        ]
      },
      "type": "Feature",
      "properties": {
        "kind": "building",
        "area": 8833,
        "sort_rank": 475,
        "addr_street": "5th Avenue",
        "height": 85,
        "volume": 750805,
        "source": "openstreetmap.org",
        "min_zoom": 13,
        "addr_housenumber": "768",
        "id": 265147728,
        "scale_rank": 1
      }
    },
```

There is, however, a [duplicate Plaza Hotel in the OSM data](http://www.openstreetmap.org/way/487846229#map=19/40.76447/-73.97447), but it doesn't appear in our zoom 15 tile. It is present in the zoom 16, but because it's a degenerate self-intersecting shape, it's reduced to a very small triangular sliver.

The building next door, 22 Central Park S, has a [height of 32.5m in the OSM data](http://www.openstreetmap.org/way/265147723#map=19/40.76478/-73.97477), and the JSON for tile `15/9650/12313` shows the same height:

```json
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -73.974887,
              40.764675
            ],
            [
              -73.974725,
              40.764905
            ],
            [
              -73.974652,
              40.764876
            ],
            [
              -73.974812,
              40.764645
            ],
            [
              -73.974887,
              40.764675
            ]
          ]
        ]
      },
      "type": "Feature",
      "properties": {
        "kind": "building",
        "area": 359,
        "sort_rank": 475,
        "addr_street": "Central Park South",
        "height": 32.5,
        "volume": 11667,
        "source": "openstreetmap.org",
        "min_zoom": 14,
        "addr_housenumber": "22",
        "id": 265147723,
        "scale_rank": 5
      }
    },
```

Are you using the GeoJSON, TopopJSON or MVT format files? Is the data in your screenshot from the `15/9650/12313` tile, or a different one? Please could you paste the full URL to the tile you downloaded (but without the API key, please!) so that we can investigate further?

**Comment by pyalot** [comment] 2017-05-18 12:48
> Perhaps you could give us some more information about how you're accessing the tiles, and the exact tile coordinates you're using?

This is already in the description of the bug first paragraph

> [the tile for the coordinates -73.9712724, 40.7646611](https://tile.mapzen.com/mapzen/vector/v1/buildings/15/9650/12313.json?api_key=mapzen-KkpHGEo)

> I took a look at the area you mention using one of our "house styles" called "bubble wrap", and it shows the corner of Central Park like this

![image](https://cloud.githubusercontent.com/assets/592826/26202711/b319ba4e-3bd8-11e7-89b7-271aa782ab6e.png)

Compare to the [same view of the Openstreetmap data in the CaesiumJS Demo](https://cesiumjs.org/NewYork/index.html?view=-73.97351820395487%2C40.76139320603994%2C1402.8817958843144%2C0.4835877426379727%2C-72.6947694276748%2C0.005432350027933512)

![image](https://cloud.githubusercontent.com/assets/592826/26202758/ddd2d45a-3bd8-11e7-88b5-82c64994eb86.png)

Which has significantly more detail.

**Comment by iandees** [comment] 2017-05-18 13:01
The CesiumJS Demo uses New York City's building dataset, not OSM. The same buildings dataset was imported into OSM, but they'll appear different because import brought the data into OSM differently and/or OSM doesn't support the same level of detail in geometry that the NYC buildings dataset (and CesiumJS) does.

**Comment by pyalot** [comment] 2017-05-18 13:30
> The CesiumJS Demo uses New York City's building dataset, not OSM.

That's incorrect. CaesiumJS lets you toggle between the NYC DoITT CityGML and Openstreetmap data, it's the first radio toggles in the control widget at the top right of the screen. All screenshots I took where taken from the representation of the Openstreetmap dataset.

**Comment by iandees** [comment] 2017-05-18 13:51
Ah yep! I see the toggle for OSM.

Reiterating what Matt said above, I see building height information in our map tiles. For example, [here's a geojson.io map](http://bl.ocks.org/anonymous/raw/629dac994674743b9dd25b4944dacbfa/) with the GeoJSON from [`16/19301/24627`](https://tile.mapzen.com/mapzen/vector/v1/buildings/16/19301/24627.json?api_key=mapzen-KkpHGEo):

![image](https://cloud.githubusercontent.com/assets/261584/26205253/2efc1ee2-3baf-11e7-8ef9-24c4566c0cde.png)

The Plaza Hotel has a `height` attribute set to `85` meters. The building parts for the more complicated buildings exist and have correct heights set, too.

**Comment by zerebubuth** [comment] 2017-05-18 14:24
> > Perhaps you could give us some more information about how you're accessing the tiles, and the exact tile coordinates you're using?
>
> This is already in the description of the bug first paragraph

Ah, yes! Sorry, I hadn't noticed that you'd linked to a single tile rather than a map at those coordinates.

> Compare to the same view of the Openstreetmap data in the CaesiumJS Demo
>
> Which has significantly more detail.

It's difficult to compare directly between the two, as Bubble Wrap does not attempt to render buildings realistically, just to give a squashed impression of the building in isometric for people to get their bearings. However, I do see extra detail in the roof shapes and colours of the buildings in CaesiumJS. Our data lacks the colour-related properties, but we do export `roof_shape`, `roof_height` and `roof_material`, which could be used to add detail to the model.

Was that the detail you were referring to, or was there something else?

**Comment by nvkelso** [comment] 2017-06-27 22:32
Can't reproduce, closing.

**Closed by nvkelso** 2017-06-27 22:32 UTC
