### ISSUE TITLE
Missing buildings in vector tiles

### ISSUE THREAD

**Issue by iandees** [tilezen/vector-datasource#1320] opened 2017-07-20 00:35 UTC
This came in from a report on the OSM US Slack.

Mapzen tiles don't have buildings that OSM does in Brisbane, Australia. The dashboard says we're all caught up.

![image](https://user-images.githubusercontent.com/261584/28395378-97b8dbf8-6cc1-11e7-9015-0808d1ad51a1.png)
[Mapzen](https://tangrams.github.io/carousel/?daynight#17.13573/-27.49188/152.99590)

![image](https://user-images.githubusercontent.com/261584/28395374-8fcb77ca-6cc1-11e7-8ed0-3683854b2892.png)
[OSM](http://www.openstreetmap.org/#map=17/-27.49188/152.99590)

**Comment by iandees** [comment] 2017-07-20 00:36
I forgot to add that these buildings were added as part of [this changeset](http://www.openstreetmap.org/changeset/50338777) which was closed over 3 days ago.

**Comment by nvkelso** [comment] 2017-07-20 00:43
That's odd. We do allow [residential](https://github.com/tilezen/vector-datasource/blob/71e9e131aa7044b4cb1b31163a9931054e425809/vectordatasource/meta/function.py#L100) buildings so this seems more akin to the Paris bridge problem that @zerebubuth worked to fix (by re-applying the changeset manually).

**Comment by dbdean** [comment] 2017-07-24 01:46
Hi. I'm the mapper that produced the [changeset](http://www.openstreetmap.org/changeset/50338777) in question, and complained about it not appearing in the Mapzen layer in StreetComplete on the OSM-AU slack. 

It's a bit of a pain determining if it is only this changeset (of mine) that is missing, as I have a lot of changesets around it that aren't affecting the layer shown in StreetComplete, but I have found at least one other changeset that appears to have been lost:

In addition to the changeset above, http://www.openstreetmap.org/changeset/50368587 doesn't appear to be in, but http://www.openstreetmap.org/changeset/50403909 is.

It doesn't appear to be related to the type of objects. It does look like one (or more) changesets have been missed by your backend.

**Comment by dbdean** [comment] 2017-07-24 01:55
Going back a bit further, it appears changeset http://www.openstreetmap.org/changeset/50298919 was missed too, where I changed a building tagging to a landuse.

Changeset http://www.openstreetmap.org/changeset/50298898 does appear in the map though.

So somewhere between changeset 50298898 and changeset 50403909, mapzen appears to have lost a number of changesetst.

**Comment by nvkelso** [comment] 2017-07-24 04:09
Thanks for this detailed information, we’ll have a look Monday!

**Comment by zerebubuth** [comment] 2017-07-25 15:44
Looks like the proximate cause of this was a typo in one of our config files, fixed in tilezen/chef-tilequeue#43. The typo meant that the "gardener" process we run to keep the Tiles Of Interest (TOI) set up to date was not running, and some tiles had been left to go "stale" without updates. That fix has been deployed now, and the system should be re-rendering some of those tiles which it had neglected. A quick check shows that some of them are already finished, although it may take some time to generate them all.

The typo is unlikely to be the root cause of the problem, as a non-running gardener should not have left the TOI set out of sync with the set of pre-rendered tiles in the first place. Unfortunately, it happened so long ago that the root cause is probably unknowable now. My best guess is that some transient error prevented the removal of the tile, but it wasn't flagged as an error and didn't halt the process.

**Comment by nvkelso** [comment] 2017-07-25 17:49
I see the buildings now, closing.

<img width="882" alt="screen shot 2017-07-25 at 10 48 57" src="https://user-images.githubusercontent.com/853051/28585959-f41a9a94-7126-11e7-8d0b-9798a418387b.png">

**Closed by nvkelso** 2017-07-25 17:49 UTC
