### ISSUE TITLE
Lake Victoria inverted?

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/vector-datasource#1138] opened 2016-11-24 13:09 UTC
* **What did you see?**

![lake_victoria](https://cloud.githubusercontent.com/assets/271360/20599594/d212abf2-b246-11e6-8f94-400d0c3a3d7c.gif)

Lake Victoria is fine until zoom 9, where it appears to invert, leaving its islands as lakes. It appears to correct at zoom 11.

E.g: http://tangrams.github.io/cinnabar-style/#9/-1.6834/32.6665

* **What did you expect to see?**

Lake Victoria staying more or less the same shape throughout.

It's possible that this was a data problem and will correct itself. So I'm leaving this here to remind us to come back and check after we're caught up to current data that the zoom 9 & 10 tiles got re-rendered and look okay.

**Comment by nvkelso** [comment] 2017-06-27 23:24
Can't reproduce, closing.

**Closed by nvkelso** 2017-06-27 23:24 UTC
