### ISSUE TITLE
Palace missing in POIs layer

### ISSUE THREAD

**Issue by rwrx** [tilezen/vector-datasource#1839] opened 2019-02-14 21:44 UTC
Hello, I am trying to create style similar to OpenTopoMap. I have noticed that in POIs layer there is missing palace. I am not sure if it really needs to be in POIs layer as it is in buildings layer, for example: https://www.openstreetmap.org/way/38975518 but in vector-datasource castle_type data is not available so currently there is no way to style these types of buildings similarly to OpenTopoMap - they have an icon there. Also OpenStreetMap has icon there. Is this a known issue? Thank you.

**Comment by nvkelso** [comment] 2019-02-15 00:32
The relevant OSM tags are:

`historic=castle`
`castle_type=palace`

**Comment by nvkelso** [comment] 2019-02-15 00:33
Duplicate of: https://github.com/tilezen/vector-datasource/issues/1652.

**Closed by nvkelso** 2019-02-15 00:33 UTC
