### ISSUE TITLE
provide surface data also on earlier levels

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1313] opened 2017-07-17 09:20 UTC
* **What did you see?**
on z 14.7 surface data is no provided for displayed roads

* **What did you expect to see?**
surface data

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  
* **Screenshot?** _Props for animated gifs._
On zooming out I would prefer to keep ability do display surface data for roads.

![preview](https://user-images.githubusercontent.com/899988/28261980-aa427144-6ae1-11e7-9d8d-0ac546c2536d.gif)
https://mapzen.com/tangram/play/?#14.7500/50.1363/19.9045

My map style (bicycle-focused, therefore surface is important and road class ignored) - https://github.com/matkoniecz/StreetComplete/blob/fork/app/src/main/assets/my-style.yaml

**Comment by nvkelso** [comment] 2017-07-17 16:32
Duplicate of https://github.com/tilezen/vector-datasource/issues/1252, which is scheduled for later this summer.

**Closed by nvkelso** 2017-07-17 16:32 UTC
