### ISSUE TITLE
confused by testing on live data

### ISSUE THREAD

**Issue by matkoniecz** [tilezen/vector-datasource#1321] opened 2017-07-20 12:03 UTC
* **What did you see?**

I am trying to run tests (as preparation for potential PR fixing https://github.com/tilezen/vector-datasource/issues/1273).

It seems that integration tests download live OSM data and run tests on this data.

As result for example https://github.com/tilezen/vector-datasource/blob/master/integration-test/1020-roads-surface.py tests both

- that generation of surface data in vector tiles is working correctly
- that 190536019 was not edited with surface change

I base my understanding on reading https://github.com/tilezen/vector-datasource/blob/master/TESTS.md https://github.com/tilezen/vector-datasource/blob/master/CONTRIBUTING.md and looking at tests like https://github.com/tilezen/vector-datasource/blob/master/integration-test/1020-roads-surface.py

* **What did you expect to see?**

Edits to OSM are not going to result in false negatives.

I would expect that either bundling data with tests (as .osm files or something similar) would be preferable - it would eliminate relying on overpass service and internet connection, edits on OSM would no longer disrupt tests.

It is also possible to obtain data from overpass at certain date - so new edits would not disturb tests.

**Comment by matkoniecz** [comment] 2017-07-20 13:41
For example there is currently proposed PR that is necessary because live data is used for testing - https://github.com/tilezen/vector-datasource/pull/1311/commits/f27680cb196865f0f6f207576ef06f4e44f31a2c

**Comment by rmarianski** [comment] 2017-07-20 14:36
Yes, the testing strategy is not ideal here, and we plan on addressing this in the near future.

**Comment by nvkelso** [comment] 2017-07-20 16:52
Good feedback, thanks! Duplicate of https://github.com/tilezen/vector-datasource/issues/923.

**Closed by nvkelso** 2017-07-20 16:52 UTC
